application: bitfocusiblog
version: experimental-grantan
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /googlefcab19a6596fa371\.html
  static_files: static/googlefcab19a6596fa371.html
  upload: static/googlefcab19a6596fa371\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: main.py
